
import { Quote } from '@/types/quote';

interface BOMItem {
  id: number;
  name: string;
  description: string;
  quantity: number;
  unitPrice: number;
  enabled: boolean;
}

export const generateQuotePDF = (
  bomItems: BOMItem[],
  quote: Quote,
  canSeePrices: boolean = true
): void => {
  // Create a new window for PDF generation
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const totalPrice = bomItems.reduce((total, item) => total + (item.quantity * item.unitPrice), 0);

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Quote Draft - ${quote.id || 'New Quote'}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
        .header { border-bottom: 2px solid #dc2626; padding-bottom: 20px; margin-bottom: 30px; }
        .logo { color: #dc2626; font-size: 24px; font-weight: bold; }
        .quote-info { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
        .info-section { background: #f8f9fa; padding: 15px; border-radius: 8px; }
        .info-title { font-weight: bold; color: #dc2626; margin-bottom: 10px; }
        .bom-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .bom-table th, .bom-table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        .bom-table th { background-color: #dc2626; color: white; }
        .bom-table tr:nth-child(even) { background-color: #f2f2f2; }
        .total-section { text-align: right; font-size: 18px; font-weight: bold; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
        @media print { body { margin: 0; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">QUALITROL</div>
        <h1>Quote Draft</h1>
        <p>Generated on: ${new Date().toLocaleDateString()}</p>
      </div>

      <div class="quote-info">
        <div class="info-section">
          <div class="info-title">Customer Information</div>
          <p><strong>Customer Name:</strong> ${quote.customerName || 'Not specified'}</p>
          <p><strong>Oracle Customer ID:</strong> ${quote.oracleCustomerId || 'Not specified'}</p>
        </div>
        <div class="info-section">
          <div class="info-title">Quote Details</div>
          <p><strong>Priority:</strong> ${quote.priority || 'Normal'}</p>
          <p><strong>Rep Involved:</strong> ${quote.isRepInvolved ? 'Yes' : 'No'}</p>
          <p><strong>Currency:</strong> ${quote.quoteCurrency || 'USD'}</p>
        </div>
      </div>

      <div class="info-section">
        <div class="info-title">Terms & Conditions</div>
        <p><strong>Shipping Terms:</strong> ${quote.shippingTerms || 'Not specified'}</p>
        <p><strong>Payment Terms:</strong> ${quote.paymentTerms || 'Not specified'}</p>
      </div>

      <h2>Bill of Materials</h2>
      <table class="bom-table">
        <thead>
          <tr>
            <th>Item</th>
            <th>Description</th>
            <th>Qty</th>
            ${canSeePrices ? '<th>Unit Price</th><th>Total</th>' : ''}
          </tr>
        </thead>
        <tbody>
          ${bomItems.map(item => `
            <tr>
              <td>${item.name}</td>
              <td>${item.description}</td>
              <td>${item.quantity}</td>
              ${canSeePrices ? `
                <td>$${item.unitPrice.toLocaleString()}</td>
                <td>$${(item.unitPrice * item.quantity).toLocaleString()}</td>
              ` : ''}
            </tr>
          `).join('')}
        </tbody>
      </table>

      ${canSeePrices ? `
        <div class="total-section">
          <p>Total: $${totalPrice.toLocaleString()}</p>
        </div>
      ` : ''}

      <div class="footer">
        <p>This is a draft quote and is subject to final approval and terms & conditions.</p>
        <p>Generated by Qualitrol Quote System</p>
      </div>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  printWindow.print();
};
