-- Update email templates to include PDF link button
UPDATE email_templates 
SET body_template = '<html><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><h2 style="color: #22c55e;">Quote Approved</h2><p>Dear {{recipient_name}},</p><p>The quote <strong>{{quote_id}}</strong> for customer <strong>{{customer_name}}</strong> has been approved.</p><div style="background: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0;"><h3 style="margin-top: 0;">Quote Details</h3><p><strong>Quote ID:</strong> {{quote_id}}</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Original Value:</strong> {{original_value}}</p><p><strong>Approved Discount:</strong> {{approved_discount}}%</p><p><strong>Final Value:</strong> {{final_value}}</p><p><strong>Approved By:</strong> {{approved_by}}</p><p><strong>Approved On:</strong> {{approved_date}}</p></div>{{#if approval_notes}}<div style="background: #e0f2fe; padding: 15px; border-radius: 5px; margin: 20px 0;"><h3 style="margin-top: 0;">Approval Notes</h3><p>{{approval_notes}}</p></div>{{/if}}<div style="text-align: center; margin: 30px 0;">{{pdf_link}}</div><p>Best regards,<br>QUALITROL Quote System</p></body></html>',
    updated_at = now()
WHERE template_type = 'quote_approved';

UPDATE email_templates 
SET body_template = '<html><body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;"><h2 style="color: #ef4444;">Quote Rejected</h2><p>Dear {{recipient_name}},</p><p>The quote <strong>{{quote_id}}</strong> for customer <strong>{{customer_name}}</strong> has been rejected.</p><div style="background: #f3f4f6; padding: 15px; border-radius: 5px; margin: 20px 0;"><h3 style="margin-top: 0;">Quote Details</h3><p><strong>Quote ID:</strong> {{quote_id}}</p><p><strong>Customer:</strong> {{customer_name}}</p><p><strong>Quote Value:</strong> {{quote_value}}</p><p><strong>Rejected By:</strong> {{rejected_by}}</p><p><strong>Rejected On:</strong> {{rejected_date}}</p></div>{{#if rejection_reason}}<div style="background: #fee2e2; padding: 15px; border-radius: 5px; margin: 20px 0;"><h3 style="margin-top: 0;">Rejection Reason</h3><p>{{rejection_reason}}</p></div>{{/if}}<div style="text-align: center; margin: 30px 0;">{{pdf_link}}</div><p>Please review the rejection reason and make necessary adjustments before resubmitting.</p><p>Best regards,<br>QUALITROL Quote System</p></body></html>',
    updated_at = now()
WHERE template_type = 'quote_rejected';